version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: smart_shipment
    ports:
      - "5432:5432"
    networks:
      - smart-network

  redis:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - smart-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - smart-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - smart-network

  config-server:
    build: 
      context: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - smart-network

  service-registry:
    build: 
      context: ./service-registry
    container_name: service-registry
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
    networks:
      - smart-network

  smart-api-gateway:
    build: 
      context: ./smart-api-gateway
    container_name: smart-api-gateway
    ports:
      - "8084:8084"
    depends_on:
      - config-server
      - service-registry
      - redis
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - SPRING_DATA_REDIS_HOST=redis
    networks:
      - smart-network

  auth-service:
    build: 
      context: ./auth-service
    container_name: auth-service
    depends_on:
      - config-server
      - service-registry
      - postgres
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/smart_shipment
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
    networks:
      - smart-network

  smart-shipment:
    build: 
      context: ./smart-shipment
    container_name: smart-shipment
    depends_on:
      - config-server
      - service-registry
      - postgres
      - kafka
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/smart_shipment
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    networks:
      - smart-network

  smart-notification:
    build: 
      context: ./smart-notification
    container_name: smart-notification
    depends_on:
      - config-server
      - service-registry
      - postgres
      - kafka
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/smart_shipment
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    networks:
      - smart-network

networks:
  smart-network:
    driver: bridge
