server.port=8083

spring.kafka.bootstrap-servers=localhost:9092

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true
resilience4j.circuitbreaker.instances.notificationService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.notificationService.slidingWindowSize=5
resilience4j.circuitbreaker.instances.notificationService.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.notificationService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.notificationService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.notificationService.permittedNumberOfCallsInHalfOpenState=2
